repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.0rc1'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
default_language_version:
    python: python3
