exclude: >
  (?x)^(
      scripts/grid/|
      scripts/to_graphviz.py
  )
repos:
- repo: https://github.com/pycqa/isort
  rev: 5.11.4
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/ambv/black
  rev: '22.12.0'
  hooks:
    - id: black
- repo: https://github.com/pycqa/flake8
  rev: '6.0.0'
  hooks:
    - id: flake8
      exclude: (tests|doc)
      additional_dependencies: [
          'flake8-builtins',
          'flake8-logging-format',
          'flake8-rst-docstrings',
          'pygments',
          'pep8-naming'
      ]
- repo: https://github.com/python-poetry/poetry
  rev: '1.3.0'
  hooks:
    - id: poetry-check
default_language_version:
    python: python3

