repos:
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
    - id: flake8
      exclude: (tests|doc)
      additional_dependencies: [
          'flake8-builtins',
          'flake8-logging-format',
          'flake8-rst-docstrings',
          'pygments',
          'pep8-naming'
      ]
default_language_version:
    python: python3
