# Use postgres/example user/password credentials
version: '3.8'

services:
  postgres:
    # container_name: postgisTestContainer
    image: postgis/postgis:14-3.4
    # image: postgis_demeter:${GITHUB_REF_SLUG}
    # build:
    #   context: .
    #   dockerfile: .postgresql/Dockerfile
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    networks:
      - app-tier
    volumes:
      - postgres:/var/lib/postgresql/data

  python:
    # image: ${REGISTRY}/${ECR_REPOSITORY}:${GITHUB_REF_SLUG}
    image: demeter:${GITHUB_REF_SLUG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    volumes:
      - ~/.ssh:/root/.ssh
    depends_on:
      - postgres
    networks:
      - app-tier

    command: tail -f /dev/null

networks:
  app-tier:
    driver: bridge

volumes:
  postgres:
    driver: local
