# Use postgres/example user/password credentials
version: '3.8'

services:
  postgres:
    container_name: postgisTestContainer
    image: postgis/postgis:14-3.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
