# Use postgres/example user/password credentials
version: '3.8'

services:
  postgres:
    # container_name: postgisTestContainer
    image: postgis/postgis:14-3.4
    # image: postgis_demeter:${GITHUB_REF_SLUG}
    # build:
    #   context: .
    #   dockerfile: .postgresql/Dockerfile
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    networks:
      - app-tier
    volumes:
      - postgres:/var/lib/postgresql/data

  python:
    image: demeter:${GITHUB_HEAD_REF_SLUG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    volumes:
      - ~/.ssh:/root/.ssh
    depends_on:
      - postgres
    networks:
      - app-tier

    command: >
      sh -cx "PGPASSWORD=$${{ env.DB_PW }} psql -h localhost -U postgres -p 5432 -c 'CREATE DATABASE "demeter-dev";' && poetry run python3 -m initialize.users && poetry run python3 -m initialize.schema.demeter --schema_name demeter && poetry run python3 -m initialize.schema.raster && poetry run python3 -m initialize.schema.weather"

networks:
  app-tier:
    driver: bridge

volumes:
  postgres:
    driver: local
