[tool.poetry]
name = "mlops-db"
version = "1.0.0"
description = ""
authors = ["Joel Larson <joel.larson@sentera.com"]

[tool.poetry.dependencies]
python = "^3.9.10"
psycopg2 = "^2.9.3"
typing_extensions = "^4.0.1"
jsonschema = "^4.4.0"


[tool.poetry.dev-dependencies]
types-jsonschema = "^4.4.1"
types.psycopg2 = "^2.9.7"
types.requests = "^2.27.10"
types.urllib3 = "^1.26.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
