name: Install Project

on:
  pull_request:
  push:
    branches: [main]

  workflow_call:
    # inputs:
    #   config-path:
    #     required: true
    #     type: string
    secrets:
      token:
        required: true
jobs:
  poetry:
    # name: Install project
    runs-on: ubuntu-latest
    env:
      working_directory: ./
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY_TRAVIS_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Register SSH key(s) for private dependencies
        # Make sure the @v0.8.0 matches the current version of the action (https://github.com/marketplace/actions/webfactory-ssh-agent)
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ env.SSH_KEY }}
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          cache: 'poetry'
      - name: Install project
        run: poetry install
